### ISSUE TITLE
Is this a complete implementation of the project

### ISSUE THREAD

**Issue by AILUOMANGALAOSHI** [razvancaramalau/MoBYv2AL#1]
some modules could not be found,such as,dnn_16enc,ResNet18E...
I tried four different value of --learner_architecture, none of which worked properly.
Looking forward to your reply

**Comment by razvancaramalau** [comment]
Thank you so much for pointing this out. My mistake of not providing the full models. Please find the updated repo. It should work from what I've just checked.
